Feat auth
instituteofai/colexga pull request #11
Opened 2021-02-19 17:44 UTC by kumarchandan

Features Added
---
- [ ] User can Login with Google
- [ ] User can Logout
- [ ] Login and Logout Button is displayed or hidden accordingly
- [ ] User information is cached (life: 24 h), loads user info from cache storage if the page is opened or refreshed again
- [ ] User information is also stored in the backend with every Submission of a task

2021-02-20 10:10 UTC, ravimashru requested changes

2021-02-20 10:10 UTC, ravimashru commented on server/config/keys.sample.js
> +};
Shouldn't we keep all these required configuration variables in a single location? We are using a `.env` file to load the `NODE_ENV` and `MONGO_URI` properties as environment variables. How about we move these properties to that file as well (e.g. as `GOOGLE_CLIENT_ID`, `GOOGLE_CLIENT_SECRET`, `GOOGLE_REDIRECT_URL` and `SESSION_KEY`) and then access them using the corresponding environment variables in our code instead of having this extra file?

2021-02-20 10:10 UTC, ravimashru commented on server/api/index.js
> +  if (req.user) {
Shouldn't this have an `else` statement? I see that whenever the homepage opens, there is a backend call made to this endpoint that never gets a response because of the missing `else` block and eventually times out and throws an error on the console.

![backend-call-forever-loading](https://user-images.githubusercontent.com/8961232/108590497-e551f700-7389-11eb-835d-c002bcdc7d38.png)

![image](https://user-images.githubusercontent.com/8961232/108590844-9a38e380-738b-11eb-827b-cfb0a75549b0.png)

2021-02-20 10:10 UTC, ravimashru commented on server/api/user.js
> +// const User = require('../models/user.model');
We can delete this file if we don't need it

2021-02-20 10:10 UTC, ravimashru commented on server/models/submission.model.js
> +  },
Do we really need to store both `displayName` and `email`? Can't we just have `email` since we assume that will uniquely identify the user (i.e. the `displayName` of a user may change when e.g. they rename themselves in their Google profile, but their email address wouldn't).

2021-02-20 10:10 UTC, ravimashru commented on server/models/user.model.js
> +  googleProfileId: {
Should we keep the name of this property Google-specific? Shouldn't we keep it generic (e.g. `identityProviderId`) so that if we ever integrate any additional identity providers in the future we don't have to mess with this schema?

2021-02-20 10:11 UTC, ravimashru commented
The Submission API tests are failing for some reason:

```
  1) Submission API
       should add a new submission to the database:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/ravimashru/projects/colexga/server/tests/submission-api.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  2) Submission API
       should return newly created submissions of a user:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/ravimashru/projects/colexga/server/tests/submission-api.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  3) Submission API
       should update details of an existing submission:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/ravimashru/projects/colexga/server/tests/submission-api.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  4) Submission API
       should delete an existing submission:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/ravimashru/projects/colexga/server/tests/submission-api.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

All the other tests pass. Am I missing something?

2021-02-20 14:15 UTC, kumarchandan commented on server/api/index.js
> +  if (req.user) {
@ravimashru Impressive Catch Bro! Fixed.

2021-02-20 14:53 UTC, kumarchandan commented
@ravimashru I have made the changes. You can review it now.
Thanks for the feedback!

2021-02-21 16:16 UTC, ravimashru approved these changes
LGTM!

2021-02-21 16:17 UTC, merged